language: node_js
node_js:
  - "0.12"
  - "0.11"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf69b46ae03c21dabce2
    on_success: always
    on_failure: always
    on_start: false